#!/usr/bin/env python3
"""
Generate data.js from beta_scores.csv and gate_assignments.csv
for use by index.html (avoids loading CSVs from filesystem in browser).
Run from project root: python scripts/embed_data.py
"""

import csv
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DATA_PROCESSED = BASE / "data" / "processed"

BETA_FIELDS = [
    "callSign",
    "airline.iata",
    "aircraft.reg",
    "PREDICTED_DELAY",
    "DELAY_BETA_NORM",
    "downstream_count",
    "departure.scheduledTime.utc",
]


def main():
    beta_path = DATA_PROCESSED / "beta_scores.csv"
    gate_path = DATA_PROCESSED / "gate_assignments.csv"
    out_path = BASE / "data.js"

    # Beta: filter source == 'YYZ', keep only required fields
    beta_data = []
    with open(beta_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if (row.get("source") or "").strip() != "YYZ":
                continue
            beta_data.append({k: row.get(k, "") for k in BETA_FIELDS})

    # Gate: full rows as list of dicts (for table columns)
    gate_data = []
    with open(gate_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        gate_data = list(reader)

    # Write data.js with const BETA_DATA and const GATE_DATA
    js_content = (
        "// Generated by embed_data.py – do not edit by hand\n"
        "const BETA_DATA = "
        + json.dumps(beta_data, ensure_ascii=False)
        + ";\n"
        "const GATE_DATA = "
        + json.dumps(gate_data, ensure_ascii=False)
        + ";\n"
    )
    out_path.write_text(js_content, encoding="utf-8")
    print(f"Wrote {out_path} ({len(beta_data)} beta rows, {len(gate_data)} gate rows)")


if __name__ == "__main__":
    main()
